<a href="https://colab.research.google.com/github/heyggun/bigdata_analysis_test/blob/main/DataManim_type2_Classification_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 작업형 2 유형

https://www.datamanim.com/dataset/03_dataq/typetwo.html#id12

## 분류 Classification

### 센서데이터 동작유형 분류 데이터

- 데이터 설명 : 센서데이터로 동작 유형 분류 (종속변수 pose : 0 ,1 구분)
- x_train: https://raw.githubusercontent.com/Datamanim/datarepo/main/muscle/x_train.csv
- y_train: https://raw.githubusercontent.com/Datamanim/datarepo/main/muscle/y_train.csv
- x_test: https://raw.githubusercontent.com/Datamanim/datarepo/main/muscle/x_test.csv
- x_label(평가용) : https://raw.githubusercontent.com/Datamanim/datarepo/main/muscle/y_test.csv
- 데이터 출처 :https://www.kaggle.com/kyr7plus/emg-4(참고, 데이터 수정)

In [2]:
import pandas as pd
import numpy as np

In [3]:
x_train = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/muscle/x_train.csv')
y_train = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/muscle/y_train.csv')
x_test = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/muscle/x_test.csv')
y_test = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/muscle/y_test.csv')

In [4]:
display(x_train.head(3))
print(x_train.shape)
display(y_train.head(3))
print(y_train.shape)

display(x_test.head(3))
print(x_test.shape)
display(y_test.head(3))
print(y_test.shape)

,ID,motion_0,motion_1,motion_2,motion_3,motion_4,motion_5,motion_6,motion_7,motion_8,...,motion_54,motion_55,motion_56,motion_57,motion_58,motion_59,motion_60,motion_61,motion_62,motion_63
0,0,1.0,-2.0,-1.0,4.0,-5.0,-4.0,1.0,0.0,-15.0,...,0.0,-1.0,-13.0,-3.0,1.0,-1.0,-32.0,-22.0,-2.0,-3.0
1,2,20.0,0.0,0.0,1.0,5.0,6.0,-52.0,18.0,15.0,...,-70.0,-55.0,-38.0,-14.0,-12.0,-8.0,-34.0,-63.0,-87.0,-77.0
2,4,1.0,-1.0,1.0,4.0,-5.0,-8.0,1.0,-3.0,-14.0,...,1.0,12.0,-25.0,0.0,0.0,3.0,2.0,-27.0,1.0,0.0

(4650, 65)

   ID  pose
0   0     1
1   2     0
2   4     1

(4650, 2)

,ID,motion_0,motion_1,motion_2,motion_3,motion_4,motion_5,motion_6,motion_7,motion_8,...,motion_54,motion_55,motion_56,motion_57,motion_58,motion_59,motion_60,motion_61,motion_62,motion_63
0,1,-12.0,-7.0,3.0,6.0,-21.0,-28.0,1.0,6.0,-18.0,...,2.0,20.0,-25.0,-2.0,1.0,0.0,12.0,-2.0,-1.0,-4.0
1,3,-9.0,-16.0,-2.0,-1.0,39.0,17.0,3.0,1.0,-9.0,...,0.0,1.0,-1.0,-5.0,-4.0,-7.0,56.0,28.0,1.0,6.0
2,8,-4.0,-1.0,-1.0,1.0,3.0,-1.0,4.0,7.0,3.0,...,-4.0,-8.0,5.0,2.0,0.0,2.0,13.0,-3.0,0.0,4.0

(1163, 65)

   ID  pose
0   1     1
1   3     1
2   8     1

(1163, 2)

In [7]:
print(len(x_train.columns))
print(len(x_train.select_dtypes(include='number').columns))

65
65

(1) scaling 없이 modeling

In [8]:
X_tr = x_train.drop(columns=['ID'])
y_tr = y_train.drop(columns=['ID'])

X_te = x_test.drop(columns=['ID'])
y_te = y_test.drop(columns=['ID'])

In [9]:
from sklearn.model_selection import train_test_split

X_train_m, X_test_m, y_train_m, y_test_m = train_test_split(X_tr, y_tr,
                                                            test_size=0.3,
                                                            random_state=2023)

print(X_train_m.shape)
print(y_train_m.shape)

print(X_test_m.shape)
print(y_test_m.shape)

(3255, 64)
(3255, 1)
(1395, 64)
(1395, 1)

In [10]:
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

In [17]:
model = RandomForestClassifier()
model.fit(X_train_m, y_train_m)
pred = model.predict_proba(X_test_m)[:,1]
pred_class = model.predict(X_test_m)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

In [15]:
from sklearn.metrics import roc_auc_score, accuracy_score, f1_score

In [18]:
print(roc_auc_score(y_test_m, pred))
print(accuracy_score(y_test_m, pred_class))
print(f1_score(y_test_m, pred_class))

0.9993175745118191
0.992831541218638
0.9927536231884058

In [19]:
pred = model.predict_proba(X_te)[:,1]
pred_class = model.predict(X_te)

print(roc_auc_score(y_te, pred))
print(accuracy_score(y_te, pred_class))
print(f1_score(y_te, pred_class))

1.0
0.998280309544282
0.9981916817359855

? 왜 이런 데이터들은 basic이 1.0, 0.99가 나와.. 미친건가